const addedText = [
  {
    id: 1,
    name: 'Product 1',
    price: '99.99',
    like: true,
    img: require('../assets/images/plant1.jpg'),
    about: 'This is about of this product',
  },
  {
    id: 2,
    name: 'Product 2',
    price: '99.99',
    like: false,
    img: require('../assets/images/plant2.jpg'),
    about: 'This is about of this product',
  },
  {
    id: 3,
    name: 'Product 3',
    price: '99.99',
    like: true,
    img: require('../assets/images/plant3.jpg'),
    about: 'This is about of this product',
  },
  {
    id: 4,
    name: 'Product 4',
    price: '99.99',
    like: true,
    img: require('../assets/images/plant1.jpg'),
    about: 'This is about of this product',
  },
  {
    id: 5,
    name: 'Product 5',
    price: '99.99',
    like: false,
    img: require('../assets/images/plant2.jpg'),
    about: 'This is about of this product',
  },
  {
    id: 6,
    name: 'Product 6',
    price: '99.99',
    like: true,
    img: require('../assets/images/plant3.jpg'),
    about: 'This is about of this product',
  },
  {
    id: 7,
    name: 'Product 7',
    price: '99.99',
    like: true,
    img: require('../assets/images/plant1.jpg'),
    about: 'This is about of this product',
  },
  {
    id: 8,
    name: 'Product 8',
    price: '99.99',
    like: false,
    img: require('../assets/images/plant2.jpg'),
    about: 'This is about of this product',
  },
  {
    id: 9,
    name: 'Product 9',
    price: '99.99',
    like: true,
    img: require('../assets/images/plant3.jpg'),
    about: 'This is about of this product',
  }
]

export default addedText;
