export const stickersData = [
  {
    id: 0,
    title: "every day",
    colorable: true,
    arr: [
      require("../assets/stickers/every_day/1.png"),
      require("../assets/stickers/every_day/2.png"),
      require("../assets/stickers/every_day/3.png"),
      require("../assets/stickers/every_day/4.png"),
      require("../assets/stickers/every_day/5.png"),
      require("../assets/stickers/every_day/6.png"),
      require("../assets/stickers/every_day/7.png"),
      require("../assets/stickers/every_day/8.png"),
      require("../assets/stickers/every_day/9.png"),
      require("../assets/stickers/every_day/10.png"),
      require("../assets/stickers/every_day/11.png"),
      require("../assets/stickers/every_day/12.png"),
      require("../assets/stickers/every_day/13.png"),
      require("../assets/stickers/every_day/14.png"),
      require("../assets/stickers/every_day/15.png"),
      require("../assets/stickers/every_day/16.png"),
      require("../assets/stickers/every_day/17.png"),
      require("../assets/stickers/every_day/18.png"),
      require("../assets/stickers/every_day/19.png"),
      require("../assets/stickers/every_day/20.png"),
      require("../assets/stickers/every_day/21.png"),
      require("../assets/stickers/every_day/22.png"),
      require("../assets/stickers/every_day/23.png"),
      require("../assets/stickers/every_day/24.png"),
      require("../assets/stickers/every_day/25.png"),
      require("../assets/stickers/every_day/26.png"),
      require("../assets/stickers/every_day/27.png"),
      require("../assets/stickers/every_day/28.png"),
      require("../assets/stickers/every_day/29.png"),
      require("../assets/stickers/every_day/30.png"),
    ],
  },
  {
    id: 1,
    title: "due weeks",
    colorable: true,
    arr: [
      require("../assets/stickers/due_weeks/1.png"),
      require("../assets/stickers/due_weeks/2.png"),
      require("../assets/stickers/due_weeks/3.png"),
      require("../assets/stickers/due_weeks/4.png"),
      require("../assets/stickers/due_weeks/5.png"),
      require("../assets/stickers/due_weeks/6.png"),
      require("../assets/stickers/due_weeks/7.png"),
      require("../assets/stickers/due_weeks/8.png"),
      require("../assets/stickers/due_weeks/9.png"),
      require("../assets/stickers/due_weeks/10.png"),
      require("../assets/stickers/due_weeks/11.png"),
      require("../assets/stickers/due_weeks/12.png"),
      require("../assets/stickers/due_weeks/13.png"),
      require("../assets/stickers/due_weeks/14.png"),
      require("../assets/stickers/due_weeks/15.png"),
      require("../assets/stickers/due_weeks/16.png"),
      require("../assets/stickers/due_weeks/17.png"),
      require("../assets/stickers/due_weeks/18.png"),
      require("../assets/stickers/due_weeks/19.png"),
      require("../assets/stickers/due_weeks/20.png"),
      require("../assets/stickers/due_weeks/21.png"),
      require("../assets/stickers/due_weeks/22.png"),
      require("../assets/stickers/due_weeks/23.png"),
      require("../assets/stickers/due_weeks/24.png"),
      require("../assets/stickers/due_weeks/25.png"),
      require("../assets/stickers/due_weeks/26.png"),
      require("../assets/stickers/due_weeks/27.png"),
      require("../assets/stickers/due_weeks/28.png"),
      require("../assets/stickers/due_weeks/29.png"),
      require("../assets/stickers/due_weeks/30.png"),
      require("../assets/stickers/due_weeks/31.png"),
      require("../assets/stickers/due_weeks/32.png"),
      require("../assets/stickers/due_weeks/33.png"),
      require("../assets/stickers/due_weeks/34.png"),
      require("../assets/stickers/due_weeks/35.png"),
      require("../assets/stickers/due_weeks/36.png"),
      require("../assets/stickers/due_weeks/37.png"),
      require("../assets/stickers/due_weeks/38.png"),
      require("../assets/stickers/due_weeks/39.png"),
      require("../assets/stickers/due_weeks/40.png"),
      require("../assets/stickers/due_weeks/41.png"),
      require("../assets/stickers/due_weeks/42.png"),
      require("../assets/stickers/due_weeks/43.png"),
      require("../assets/stickers/due_weeks/44.png"),
      require("../assets/stickers/due_weeks/45.png"),
      require("../assets/stickers/due_weeks/46.png"),
      require("../assets/stickers/due_weeks/47.png"),
      require("../assets/stickers/due_weeks/48.png"),
      require("../assets/stickers/due_weeks/49.png"),
      require("../assets/stickers/due_weeks/50.png"),
      require("../assets/stickers/due_weeks/51.png"),
      require("../assets/stickers/due_weeks/52.png"),
      require("../assets/stickers/due_weeks/53.png"),
      require("../assets/stickers/due_weeks/54.png"),
      require("../assets/stickers/due_weeks/55.png"),
      require("../assets/stickers/due_weeks/56.png"),
      require("../assets/stickers/due_weeks/57.png"),
      require("../assets/stickers/due_weeks/58.png"),
      require("../assets/stickers/due_weeks/59.png"),
      require("../assets/stickers/due_weeks/60.png"),
    ],
  },
  {
    id: 2,
    title: "status",
    colorable: true,
    mx: 37,
    arr: [
      require("../assets/stickers/status/0.png"),
      require("../assets/stickers/status/1.png"),
      require("../assets/stickers/status/2.png"),
      require("../assets/stickers/status/3.png"),
      require("../assets/stickers/status/4.png"),
      require("../assets/stickers/status/5.png"),
      require("../assets/stickers/status/6.png"),
      require("../assets/stickers/status/7.png"),
      require("../assets/stickers/status/8.png"),
      require("../assets/stickers/status/9.png"),
      require("../assets/stickers/status/10.png"),
      require("../assets/stickers/status/11.png"),
      require("../assets/stickers/status/12.png"),
      require("../assets/stickers/status/13.png"),
      require("../assets/stickers/status/14.png"),
      require("../assets/stickers/status/15.png"),
      require("../assets/stickers/status/16.png"),
      require("../assets/stickers/status/17.png"),
      require("../assets/stickers/status/18.png"),
      require("../assets/stickers/status/19.png"),
      require("../assets/stickers/status/20.png"),
      require("../assets/stickers/status/21.png"),
      require("../assets/stickers/status/22.png"),
      require("../assets/stickers/status/23.png"),
      require("../assets/stickers/status/24.png"),
      require("../assets/stickers/status/25.png"),
      require("../assets/stickers/status/26.png"),
      require("../assets/stickers/status/27.png"),
      require("../assets/stickers/status/28.png"),
      require("../assets/stickers/status/29.png"),
      require("../assets/stickers/status/30.png"),
      require("../assets/stickers/status/31.png"),
      require("../assets/stickers/status/32.png"),
      require("../assets/stickers/status/33.png"),
      require("../assets/stickers/status/34.png"),
      require("../assets/stickers/status/35.png"),
      require("../assets/stickers/status/36.png"),
      require("../assets/stickers/status/37.png"),
    ],
  },
  {
    id: 3,
    title: "birth_day",
    colorable: true,
    arr: [
      require("../assets/stickers/birth_day/1.png"),
      require("../assets/stickers/birth_day/2.png"),
      require("../assets/stickers/birth_day/3.png"),
      require("../assets/stickers/birth_day/4.png"),
      require("../assets/stickers/birth_day/5.png"),
      require("../assets/stickers/birth_day/6.png"),
      require("../assets/stickers/birth_day/7.png"),
      require("../assets/stickers/birth_day/8.png"),
      require("../assets/stickers/birth_day/9.png"),
      require("../assets/stickers/birth_day/10.png"),
      require("../assets/stickers/birth_day/11.png"),
      require("../assets/stickers/birth_day/12.png"),
      require("../assets/stickers/birth_day/13.png"),
      require("../assets/stickers/birth_day/14.png"),
      require("../assets/stickers/birth_day/15.png"),
      require("../assets/stickers/birth_day/16.png"),
      require("../assets/stickers/birth_day/17.png"),
      require("../assets/stickers/birth_day/18.png"),
      require("../assets/stickers/birth_day/19.png"),
      require("../assets/stickers/birth_day/20.png"),
      require("../assets/stickers/birth_day/21.png"),
      require("../assets/stickers/birth_day/22.png"),
      require("../assets/stickers/birth_day/23.png"),
      require("../assets/stickers/birth_day/24.png"),
      require("../assets/stickers/birth_day/25.png"),
      require("../assets/stickers/birth_day/26.png"),
      require("../assets/stickers/birth_day/27.png"),
      require("../assets/stickers/birth_day/28.png"),
      require("../assets/stickers/birth_day/29.png"),
      require("../assets/stickers/birth_day/30.png"),
      require("../assets/stickers/birth_day/31.png"),
      require("../assets/stickers/birth_day/32.png"),
      require("../assets/stickers/birth_day/33.png"),
      require("../assets/stickers/birth_day/34.png"),
      require("../assets/stickers/birth_day/35.png"),
      require("../assets/stickers/birth_day/36.png"),
      require("../assets/stickers/birth_day/37.png"),
      require("../assets/stickers/birth_day/38.png"),
      require("../assets/stickers/birth_day/39.png"),
      require("../assets/stickers/birth_day/40.png"),
    ],
  },
  {
    id: 4,
    title: "hearts",
    colorable: true,
    arr: [
      require("../assets/stickers/hearts/1.png"),
      require("../assets/stickers/hearts/2.png"),
      require("../assets/stickers/hearts/3.png"),
      require("../assets/stickers/hearts/4.png"),
      require("../assets/stickers/hearts/5.png"),
      require("../assets/stickers/hearts/6.png"),
      require("../assets/stickers/hearts/7.png"),
      require("../assets/stickers/hearts/8.png"),
      require("../assets/stickers/hearts/9.png"),
      require("../assets/stickers/hearts/10.png"),
      require("../assets/stickers/hearts/11.png"),
      require("../assets/stickers/hearts/12.png"),
      require("../assets/stickers/hearts/13.png"),
      require("../assets/stickers/hearts/14.png"),
      require("../assets/stickers/hearts/15.png"),
      require("../assets/stickers/hearts/16.png"),
      require("../assets/stickers/hearts/17.png"),
      require("../assets/stickers/hearts/18.png"),
      require("../assets/stickers/hearts/19.png"),
      require("../assets/stickers/hearts/20.png"),
    ],
  },
  {
    id: 5,
    title: "boy_girl",
    colorable: true,
    arr: [
      require("../assets/stickers/boy_girl/1.png"),
      require("../assets/stickers/boy_girl/2.png"),
      require("../assets/stickers/boy_girl/3.png"),
      require("../assets/stickers/boy_girl/4.png"),
      require("../assets/stickers/boy_girl/5.png"),
      require("../assets/stickers/boy_girl/6.png"),
      require("../assets/stickers/boy_girl/7.png"),
      require("../assets/stickers/boy_girl/8.png"),
      require("../assets/stickers/boy_girl/9.png"),
      require("../assets/stickers/boy_girl/10.png"),
      require("../assets/stickers/boy_girl/11.png"),
      require("../assets/stickers/boy_girl/12.png"),
      require("../assets/stickers/boy_girl/13.png"),
      require("../assets/stickers/boy_girl/14.png"),
      require("../assets/stickers/boy_girl/15.png"),
      require("../assets/stickers/boy_girl/16.png"),
    ],
  },
  {
    id: 6,
    title: "belly_on",
    colorable: true,
    arr: [
      require("../assets/stickers/belly_on/1.png"),
      require("../assets/stickers/belly_on/2.png"),
      require("../assets/stickers/belly_on/3.png"),
      require("../assets/stickers/belly_on/4.png"),
      require("../assets/stickers/belly_on/5.png"),
      require("../assets/stickers/belly_on/6.png"),
      require("../assets/stickers/belly_on/7.png"),
      require("../assets/stickers/belly_on/8.png"),
      require("../assets/stickers/belly_on/9.png"),
      require("../assets/stickers/belly_on/10.png"),
      require("../assets/stickers/belly_on/11.png"),
      require("../assets/stickers/belly_on/12.png"),
      require("../assets/stickers/belly_on/13.png"),
      require("../assets/stickers/belly_on/14.png"),
      require("../assets/stickers/belly_on/15.png"),
    ],
  },
  {
    id: 7,
    title: "shape",
    colorable: true,
    arr: [
      require("../assets/stickers/shape/1.png"),
      require("../assets/stickers/shape/2.png"),
      require("../assets/stickers/shape/3.png"),
      require("../assets/stickers/shape/4.png"),
      require("../assets/stickers/shape/5.png"),
      require("../assets/stickers/shape/6.png"),
      require("../assets/stickers/shape/7.png"),
      require("../assets/stickers/shape/8.png"),
      require("../assets/stickers/shape/9.png"),
      require("../assets/stickers/shape/10.png"),
      require("../assets/stickers/shape/11.png"),
      require("../assets/stickers/shape/12.png"),
      require("../assets/stickers/shape/13.png"),
      require("../assets/stickers/shape/14.png"),
      require("../assets/stickers/shape/15.png"),
      require("../assets/stickers/shape/16.png"),
      require("../assets/stickers/shape/17.png"),
      require("../assets/stickers/shape/18.png"),
      require("../assets/stickers/shape/19.png"),
      require("../assets/stickers/shape/20.png"),
    ],
  },
  {
    id: 8,
    title: "stars",
    colorable: true,
    arr: [
      require("../assets/stickers/stars/1.png"),
      require("../assets/stickers/stars/2.png"),
      require("../assets/stickers/stars/3.png"),
      require("../assets/stickers/stars/4.png"),
      require("../assets/stickers/stars/5.png"),
      require("../assets/stickers/stars/6.png"),
      require("../assets/stickers/stars/7.png"),
      require("../assets/stickers/stars/8.png"),
      require("../assets/stickers/stars/9.png"),
      require("../assets/stickers/stars/10.png"),
      require("../assets/stickers/stars/11.png"),
      require("../assets/stickers/stars/12.png"),
      require("../assets/stickers/stars/13.png"),
      require("../assets/stickers/stars/14.png"),
      require("../assets/stickers/stars/15.png"),
      require("../assets/stickers/stars/16.png"),
      require("../assets/stickers/stars/17.png"),
      require("../assets/stickers/stars/18.png"),
      require("../assets/stickers/stars/19.png"),
      require("../assets/stickers/stars/20.png"),
    ],
  },
  {
    id: 9,
    title: "fun",
    colorable: true,
    arr: [
      require("../assets/stickers/fun/1.png"),
      require("../assets/stickers/fun/2.png"),
      require("../assets/stickers/fun/3.png"),
      require("../assets/stickers/fun/4.png"),
      require("../assets/stickers/fun/5.png"),
      require("../assets/stickers/fun/6.png"),
      require("../assets/stickers/fun/7.png"),
      require("../assets/stickers/fun/8.png"),
      require("../assets/stickers/fun/9.png"),
      require("../assets/stickers/fun/10.png"),
      require("../assets/stickers/fun/11.png"),
      require("../assets/stickers/fun/12.png"),
      require("../assets/stickers/fun/13.png"),
      require("../assets/stickers/fun/14.png"),
      require("../assets/stickers/fun/15.png"),
    ],
  },
  {
    id: 10,
    title: "mom_dad",
    colorable: true,
    arr: [
      require("../assets/stickers/mom_dad/1.png"),
      require("../assets/stickers/mom_dad/2.png"),
      require("../assets/stickers/mom_dad/3.png"),
      require("../assets/stickers/mom_dad/4.png"),
      require("../assets/stickers/mom_dad/5.png"),
      require("../assets/stickers/mom_dad/6.png"),
      require("../assets/stickers/mom_dad/7.png"),
      require("../assets/stickers/mom_dad/8.png"),
      require("../assets/stickers/mom_dad/9.png"),
      require("../assets/stickers/mom_dad/10.png"),
      require("../assets/stickers/mom_dad/11.png"),
      require("../assets/stickers/mom_dad/12.png"),
      require("../assets/stickers/mom_dad/13.png"),
      require("../assets/stickers/mom_dad/14.png"),
      require("../assets/stickers/mom_dad/15.png"),
      require("../assets/stickers/mom_dad/16.png"),
      require("../assets/stickers/mom_dad/17.png"),
      require("../assets/stickers/mom_dad/18.png"),
      require("../assets/stickers/mom_dad/19.png"),
      require("../assets/stickers/mom_dad/20.png"),
    ],
  },
  {
    id: 11,
    title: "food",
    colorable: false,
    arr: [
      require("../assets/stickers/food/1.png"),
      require("../assets/stickers/food/2.png"),
      require("../assets/stickers/food/3.png"),
      require("../assets/stickers/food/4.png"),
      require("../assets/stickers/food/5.png"),
      require("../assets/stickers/food/6.png"),
      require("../assets/stickers/food/7.png"),
      require("../assets/stickers/food/8.png"),
      require("../assets/stickers/food/9.png"),
      require("../assets/stickers/food/10.png"),
      require("../assets/stickers/food/11.png"),
      require("../assets/stickers/food/12.png"),
      require("../assets/stickers/food/13.png"),
      require("../assets/stickers/food/14.png"),
      require("../assets/stickers/food/15.png"),
      require("../assets/stickers/food/16.png"),
      require("../assets/stickers/food/17.png"),
      require("../assets/stickers/food/18.png"),
      require("../assets/stickers/food/19.png"),
      require("../assets/stickers/food/20.png"),
      require("../assets/stickers/food/21.png"),
      require("../assets/stickers/food/22.png"),
      require("../assets/stickers/food/23.png"),
      require("../assets/stickers/food/24.png"),
      require("../assets/stickers/food/25.png"),
      require("../assets/stickers/food/26.png"),
      require("../assets/stickers/food/27.png"),
      require("../assets/stickers/food/28.png"),
      require("../assets/stickers/food/29.png"),
      require("../assets/stickers/food/30.png"),
      require("../assets/stickers/food/31.png"),
      require("../assets/stickers/food/32.png"),
      require("../assets/stickers/food/33.png"),
      require("../assets/stickers/food/34.png"),
      require("../assets/stickers/food/35.png"),
      require("../assets/stickers/food/36.png"),
      require("../assets/stickers/food/37.png"),
      require("../assets/stickers/food/38.png"),
      require("../assets/stickers/food/39.png"),
      require("../assets/stickers/food/40.png"),
    ],
  },
  {
    id: 12,
    title: "bottle",
    colorable: false,
    arr: [
      require("../assets/stickers/bottle/1.png"),
      require("../assets/stickers/bottle/2.png"),
      require("../assets/stickers/bottle/3.png"),
      require("../assets/stickers/bottle/4.png"),
      require("../assets/stickers/bottle/5.png"),
      require("../assets/stickers/bottle/6.png"),
      require("../assets/stickers/bottle/7.png"),
      require("../assets/stickers/bottle/8.png"),
      require("../assets/stickers/bottle/9.png"),
      require("../assets/stickers/bottle/10.png"),
      require("../assets/stickers/bottle/11.png"),
      require("../assets/stickers/bottle/12.png"),
      require("../assets/stickers/bottle/13.png"),
      require("../assets/stickers/bottle/14.png"),
      require("../assets/stickers/bottle/15.png"),
      require("../assets/stickers/bottle/16.png"),
      require("../assets/stickers/bottle/17.png"),
      require("../assets/stickers/bottle/18.png"),
      require("../assets/stickers/bottle/19.png"),
      require("../assets/stickers/bottle/20.png"),
      require("../assets/stickers/bottle/21.png"),
      require("../assets/stickers/bottle/22.png"),
      require("../assets/stickers/bottle/23.png"),
      require("../assets/stickers/bottle/24.png"),
      require("../assets/stickers/bottle/25.png"),
      require("../assets/stickers/bottle/26.png"),
      require("../assets/stickers/bottle/27.png"),
      require("../assets/stickers/bottle/28.png"),
      require("../assets/stickers/bottle/29.png"),
      require("../assets/stickers/bottle/30.png"),
      require("../assets/stickers/bottle/31.png"),
      require("../assets/stickers/bottle/32.png"),
      require("../assets/stickers/bottle/33.png"),
      require("../assets/stickers/bottle/34.png"),
      require("../assets/stickers/bottle/35.png"),
      require("../assets/stickers/bottle/36.png"),
      require("../assets/stickers/bottle/37.png"),
      require("../assets/stickers/bottle/38.png"),
      require("../assets/stickers/bottle/39.png"),
      require("../assets/stickers/bottle/40.png"),
    ],
  },
  {
    id: 13,
    title: "clothes",
    colorable: false,
    arr: [
      require("../assets/stickers/clothes/1.png"),
      require("../assets/stickers/clothes/2.png"),
      require("../assets/stickers/clothes/3.png"),
      require("../assets/stickers/clothes/4.png"),
      require("../assets/stickers/clothes/5.png"),
      require("../assets/stickers/clothes/6.png"),
      require("../assets/stickers/clothes/7.png"),
      require("../assets/stickers/clothes/8.png"),
      require("../assets/stickers/clothes/9.png"),
      require("../assets/stickers/clothes/10.png"),
      require("../assets/stickers/clothes/11.png"),
      require("../assets/stickers/clothes/12.png"),
      require("../assets/stickers/clothes/13.png"),
      require("../assets/stickers/clothes/14.png"),
      require("../assets/stickers/clothes/15.png"),
      require("../assets/stickers/clothes/16.png"),
      require("../assets/stickers/clothes/17.png"),
      require("../assets/stickers/clothes/18.png"),
      require("../assets/stickers/clothes/19.png"),
      require("../assets/stickers/clothes/20.png"),
      require("../assets/stickers/clothes/21.png"),
      require("../assets/stickers/clothes/22.png"),
      require("../assets/stickers/clothes/23.png"),
      require("../assets/stickers/clothes/24.png"),
      require("../assets/stickers/clothes/25.png"),
      require("../assets/stickers/clothes/26.png"),
      require("../assets/stickers/clothes/27.png"),
      require("../assets/stickers/clothes/28.png"),
      require("../assets/stickers/clothes/29.png"),
      require("../assets/stickers/clothes/30.png"),
      require("../assets/stickers/clothes/31.png"),
      require("../assets/stickers/clothes/32.png"),
      require("../assets/stickers/clothes/33.png"),
      require("../assets/stickers/clothes/34.png"),
      require("../assets/stickers/clothes/35.png"),
      require("../assets/stickers/clothes/36.png"),
      require("../assets/stickers/clothes/37.png"),
      require("../assets/stickers/clothes/38.png"),
      require("../assets/stickers/clothes/39.png"),
      require("../assets/stickers/clothes/40.png"),
    ],
  },
  {
    id: 14,
    title: "animals",
    colorable: false,
    arr: [
      require("../assets/stickers/animals/1.png"),
      require("../assets/stickers/animals/2.png"),
      require("../assets/stickers/animals/3.png"),
      require("../assets/stickers/animals/4.png"),
      require("../assets/stickers/animals/5.png"),
      require("../assets/stickers/animals/6.png"),
      require("../assets/stickers/animals/7.png"),
      require("../assets/stickers/animals/8.png"),
      require("../assets/stickers/animals/9.png"),
      require("../assets/stickers/animals/10.png"),
      require("../assets/stickers/animals/11.png"),
      require("../assets/stickers/animals/12.png"),
      require("../assets/stickers/animals/13.png"),
      require("../assets/stickers/animals/14.png"),
      require("../assets/stickers/animals/15.png"),
      require("../assets/stickers/animals/16.png"),
      require("../assets/stickers/animals/17.png"),
      require("../assets/stickers/animals/18.png"),
      require("../assets/stickers/animals/19.png"),
      require("../assets/stickers/animals/20.png"),
      require("../assets/stickers/animals/21.png"),
      require("../assets/stickers/animals/22.png"),
      require("../assets/stickers/animals/23.png"),
      require("../assets/stickers/animals/24.png"),
      require("../assets/stickers/animals/25.png"),
      require("../assets/stickers/animals/26.png"),
      require("../assets/stickers/animals/27.png"),
      require("../assets/stickers/animals/28.png"),
      require("../assets/stickers/animals/29.png"),
      require("../assets/stickers/animals/30.png"),
      require("../assets/stickers/animals/31.png"),
      require("../assets/stickers/animals/32.png"),
      require("../assets/stickers/animals/33.png"),
      require("../assets/stickers/animals/34.png"),
      require("../assets/stickers/animals/35.png"),
      require("../assets/stickers/animals/36.png"),
      require("../assets/stickers/animals/37.png"),
      require("../assets/stickers/animals/38.png"),
      require("../assets/stickers/animals/39.png"),
      require("../assets/stickers/animals/40.png"),
      require("../assets/stickers/animals/41.png"),
      require("../assets/stickers/animals/42.png"),
      require("../assets/stickers/animals/43.png"),
      require("../assets/stickers/animals/44.png"),
      require("../assets/stickers/animals/45.png"),
      require("../assets/stickers/animals/46.png"),
      require("../assets/stickers/animals/47.png"),
      require("../assets/stickers/animals/48.png"),
      require("../assets/stickers/animals/49.png"),
      require("../assets/stickers/animals/50.png"),
    ],
  },
  {
    id: 15,
    title: "sweet",
    colorable: false,
    arr: [
      require("../assets/stickers/sweet/1.png"),
      require("../assets/stickers/sweet/2.png"),
      require("../assets/stickers/sweet/3.png"),
      require("../assets/stickers/sweet/4.png"),
      require("../assets/stickers/sweet/5.png"),
      require("../assets/stickers/sweet/6.png"),
      require("../assets/stickers/sweet/7.png"),
      require("../assets/stickers/sweet/8.png"),
      require("../assets/stickers/sweet/9.png"),
      require("../assets/stickers/sweet/10.png"),
      require("../assets/stickers/sweet/11.png"),
      require("../assets/stickers/sweet/12.png"),
      require("../assets/stickers/sweet/13.png"),
      require("../assets/stickers/sweet/14.png"),
      require("../assets/stickers/sweet/15.png"),
      require("../assets/stickers/sweet/16.png"),
      require("../assets/stickers/sweet/17.png"),
      require("../assets/stickers/sweet/18.png"),
      require("../assets/stickers/sweet/19.png"),
      require("../assets/stickers/sweet/20.png"),
    ],
  },
  {
    id: 16,
    title: "baby",
    colorable: false,
    arr: [
      require("../assets/stickers/baby/1.png"),
      require("../assets/stickers/baby/2.png"),
      require("../assets/stickers/baby/3.png"),
      require("../assets/stickers/baby/4.png"),
      require("../assets/stickers/baby/5.png"),
      require("../assets/stickers/baby/6.png"),
      require("../assets/stickers/baby/7.png"),
      require("../assets/stickers/baby/8.png"),
      require("../assets/stickers/baby/9.png"),
      require("../assets/stickers/baby/10.png"),
      require("../assets/stickers/baby/11.png"),
      require("../assets/stickers/baby/12.png"),
      require("../assets/stickers/baby/13.png"),
      require("../assets/stickers/baby/14.png"),
      require("../assets/stickers/baby/15.png"),
      require("../assets/stickers/baby/16.png"),
      require("../assets/stickers/baby/17.png"),
      require("../assets/stickers/baby/18.png"),
      require("../assets/stickers/baby/19.png"),
      require("../assets/stickers/baby/20.png"),
      require("../assets/stickers/baby/21.png"),
      require("../assets/stickers/baby/22.png"),
      require("../assets/stickers/baby/23.png"),
      require("../assets/stickers/baby/24.png"),
      require("../assets/stickers/baby/25.png"),
      require("../assets/stickers/baby/26.png"),
      require("../assets/stickers/baby/27.png"),
      require("../assets/stickers/baby/28.png"),
      require("../assets/stickers/baby/29.png"),
      require("../assets/stickers/baby/30.png"),
    ],
  },
  {
    id: 17,
    title: "mask",
    colorable: false,
    arr: [
      require("../assets/stickers/mask/1.png"),
      require("../assets/stickers/mask/2.png"),
      require("../assets/stickers/mask/3.png"),
      require("../assets/stickers/mask/4.png"),
      require("../assets/stickers/mask/5.png"),
      require("../assets/stickers/mask/6.png"),
      require("../assets/stickers/mask/7.png"),
      require("../assets/stickers/mask/8.png"),
      require("../assets/stickers/mask/9.png"),
      require("../assets/stickers/mask/10.png"),
      require("../assets/stickers/mask/11.png"),
      require("../assets/stickers/mask/12.png"),
      require("../assets/stickers/mask/13.png"),
      require("../assets/stickers/mask/14.png"),
      require("../assets/stickers/mask/15.png"),
      require("../assets/stickers/mask/16.png"),
      require("../assets/stickers/mask/17.png"),
      require("../assets/stickers/mask/18.png"),
      require("../assets/stickers/mask/19.png"),
      require("../assets/stickers/mask/20.png"),
    ],
  },
];
